export default [[[{'id': 'left-center', 'label': 'left-center', 'value': 3},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 2},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 4},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 1},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 4},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 2},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 4},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 1},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 1},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 2},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 4},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 2},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 3},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 0},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 1},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 2},
{'id': 'right-center', 'label': 'right-center', 'value': 0}]],
[[{'id': 'left-center', 'label': 'left-center', 'value': 6},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 4},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 1},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 1},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 4},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 1},
{'id': 'right-center', 'label': 'right-center', 'value': 1}],
[{'id': 'left-center', 'label': 'left-center', 'value': 2},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 1},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 1},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 4},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 1},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 1},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 3},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 1},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 1},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 3},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 1},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 2},
{'id': 'right-center', 'label': 'right-center', 'value': 0}]],
[[{'id': 'left-center', 'label': 'left-center', 'value': 3},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 2},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 3},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 1},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 1},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 1},
{'id': 'right', 'label': 'right', 'value': 2},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 2},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 2},
{'id': 'right', 'label': 'right', 'value': 1},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 4},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 3},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 1},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 3},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 0}]],
[[{'id': 'left-center', 'label': 'left-center', 'value': 2},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 1},
{'id': 'right', 'label': 'right', 'value': 3},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 0},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 3},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 2}],
[{'id': 'left-center', 'label': 'left-center', 'value': 0},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 4},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 2}],
[{'id': 'left-center', 'label': 'left-center', 'value': 0},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 4},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 2}],
[{'id': 'left-center', 'label': 'left-center', 'value': 0},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 3},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 3}],
[{'id': 'left-center', 'label': 'left-center', 'value': 0},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 5},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 1}],
[{'id': 'left-center', 'label': 'left-center', 'value': 1},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 4},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 0}]],
[[{'id': 'left-center', 'label': 'left-center', 'value': 5},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 1},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 5},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 1},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 2},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 4},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 2},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 4},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 2},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 1},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 2},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 4},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 1},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 1},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 5},
{'id': 'right-center', 'label': 'right-center', 'value': 0}]],
[[{'id': 'left-center', 'label': 'left-center', 'value': 6},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 5},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 1},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 5},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 1},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 5},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 1},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 4},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 2},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 5},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 1},
{'id': 'right-center', 'label': 'right-center', 'value': 0}],
[{'id': 'left-center', 'label': 'left-center', 'value': 6},
{'id': 'nan', 'label': 'nan', 'value': 0},
{'id': 'left ', 'label': 'left ', 'value': 0},
{'id': 'right', 'label': 'right', 'value': 0},
{'id': 'least bias', 'label': 'least bias', 'value': 0},
{'id': 'right-center', 'label': 'right-center', 'value': 0}]]]