// export default [
//   {
//     "country": "AD",
//     "hot dog": 12,
//     "hot dogColor": "hsl(255, 70%, 50%)",
//     "burger": 29,
//     "burgerColor": "hsl(72, 70%, 50%)",
//     "sandwich": 147,
//     "sandwichColor": "hsl(16, 70%, 50%)",
//     "kebab": 169,
//     "kebabColor": "hsl(84, 70%, 50%)",
//     "fries": 88,
//     "friesColor": "hsl(257, 70%, 50%)",
//     "donut": 81,
//     "donutColor": "hsl(169, 70%, 50%)"
//   },
//   {
//     "country": "AE",
//     "hot dog": 2,
//     "hot dogColor": "hsl(193, 70%, 50%)",
//     "burger": 144,
//     "burgerColor": "hsl(105, 70%, 50%)",
//     "sandwich": 159,
//     "sandwichColor": "hsl(300, 70%, 50%)",
//     "kebab": 66,
//     "kebabColor": "hsl(242, 70%, 50%)",
//     "fries": 50,
//     "friesColor": "hsl(359, 70%, 50%)",
//     "donut": 152,
//     "donutColor": "hsl(160, 70%, 50%)"
//   },
//   {
//     "country": "AF",
//     "hot dog": 90,
//     "hot dogColor": "hsl(52, 70%, 50%)",
//     "burger": 20,
//     "burgerColor": "hsl(136, 70%, 50%)",
//     "sandwich": 29,
//     "sandwichColor": "hsl(222, 70%, 50%)",
//     "kebab": 56,
//     "kebabColor": "hsl(134, 70%, 50%)",
//     "fries": 160,
//     "friesColor": "hsl(44, 70%, 50%)",
//     "donut": 128,
//     "donutColor": "hsl(337, 70%, 50%)"
//   },
//   {
//     "country": "AG",
//     "hot dog": 149,
//     "hot dogColor": "hsl(79, 70%, 50%)",
//     "burger": 38,
//     "burgerColor": "hsl(316, 70%, 50%)",
//     "sandwich": 62,
//     "sandwichColor": "hsl(132, 70%, 50%)",
//     "kebab": 146,
//     "kebabColor": "hsl(60, 70%, 50%)",
//     "fries": 142,
//     "friesColor": "hsl(130, 70%, 50%)",
//     "donut": 99,
//     "donutColor": "hsl(340, 70%, 50%)"
//   },
//   {
//     "country": "AI",
//     "hot dog": 77,
//     "hot dogColor": "hsl(273, 70%, 50%)",
//     "burger": 135,
//     "burgerColor": "hsl(120, 70%, 50%)",
//     "sandwich": 134,
//     "sandwichColor": "hsl(103, 70%, 50%)",
//     "kebab": 84,
//     "kebabColor": "hsl(257, 70%, 50%)",
//     "fries": 9,
//     "friesColor": "hsl(318, 70%, 50%)",
//     "donut": 94,
//     "donutColor": "hsl(115, 70%, 50%)"
//   },
//   {
//     "country": "AL",
//     "hot dog": 164,
//     "hot dogColor": "hsl(55, 70%, 50%)",
//     "burger": 96,
//     "burgerColor": "hsl(78, 70%, 50%)",
//     "sandwich": 107,
//     "sandwichColor": "hsl(230, 70%, 50%)",
//     "kebab": 60,
//     "kebabColor": "hsl(43, 70%, 50%)",
//     "fries": 54,
//     "friesColor": "hsl(172, 70%, 50%)",
//     "donut": 155,
//     "donutColor": "hsl(313, 70%, 50%)"
//   },
//   {
//     "country": "AM",
//     "hot dog": 60,
//     "hot dogColor": "hsl(69, 70%, 50%)",
//     "burger": 107,
//     "burgerColor": "hsl(21, 70%, 50%)",
//     "sandwich": 104,
//     "sandwichColor": "hsl(189, 70%, 50%)",
//     "kebab": 105,
//     "kebabColor": "hsl(357, 70%, 50%)",
//     "fries": 103,
//     "friesColor": "hsl(193, 70%, 50%)",
//     "donut": 89,
//     "donutColor": "hsl(19, 70%, 50%)"
//   }
// ]
// export default [


// {'channel': 'today', 'left_users': 9, "left_usersColor": "hsl(255, 70%, 50%)", 'right_users': 8, "right_usersColor": "hsl(72, 70%, 50%)", 'control_users': 12, "control_usersColor": "hsl(16, 70%, 50%)"}, 
// {'channel': 'lastweektonight', 'left_users': 2, 'right_users': 2, 'control_users': 2}, 
// {'channel': 'abc news', 'left_users': 2, 'right_users': 0, 'control_users': 1}, 
// {'channel': 'cnn', 'left_users': 8, 'right_users': 7, 'control_users': 3}, 
// {'channel': 'cnbc television', 'left_users': 0, 'right_users': 1, 'control_users': 1}, 
// {'channel': 'yahoo finance', 'left_users': 0, 'right_users': 0, 'control_users': 7}, 
// {'channel': 'cbs this morning', 'left_users': 0, 'right_users': 0, 'control_users': 1}, 
// {'channel': 'fox news', 'left_users': 0, 'right_users': 31, 'control_users': 1},
// {'channel': 'sky news', 'left_users': 19, 'right_users': 1, 'control_users': 17}, 
// {'channel': 'nbc news', 'left_users': 10, 'right_users': 6, 'control_users': 10}, 
// {'channel': 'cnbc', 'left_users': 0, 'right_users': 0, 'control_users': 1}, 
// {'channel': 'c-span', 'left_users': 0, 'right_users': 0, 'control_users': 5}, 
// {'channel': 'cbs news', 'left_users': 3, 'right_users': 0, 'control_users': 10}, 
// {'channel': 'pbs newshour', 'left_users': 22, 'right_users': 7, 'control_users': 18}, 
// {'channel': 'hbo', 'left_users': 0, 'right_users': 2, 'control_users': 2}, 
// {'channel': 'msnbc', 'left_users': 4, 'right_users': 0, 'control_users': 1}, 
// {'channel': 'washington post', 'left_users': 1, 'right_users': 0, 'control_users': 1}, 
// {'channel': 'inside edition', 'left_users': 1, 'right_users': 2, 'control_users': 1}, 
// {'channel': 'coffee shop ambience', 'left_users': 0, 'right_users': 0, 'control_users': 0}, 
// {'channel': 'touch your heart', 'left_users': 0, 'right_users': 0, 'control_users': 0}, 
// {'channel': '60 minutes', 'left_users': 0, 'right_users': 2, 'control_users': 0}, 
// {'channel': 'the late show with stephen colbert', 'left_users': 0, 'right_users': 0, 'control_users': 0}, 
// {'channel': 'real time with bill maher', 'left_users': 0, 'right_users': 0, 'control_users': 0}, 
// {'channel': 'late night with seth meyers', 'left_users': 0, 'right_users': 0, 'control_users': 0}, 
// {'channel': 'k&m productions - speakers & shows', 'left_users': 1, 'right_users': 0, 'control_users': 0}, 
// {'channel': 'openlearn from the open university', 'left_users': 1, 'right_users': 0, 'control_users': 0}, 
// {'channel': 'mr fabio', 'left_users': 1, 'right_users': 0, 'control_users': 0}, 
// {'channel': 'estudio arkano', 'left_users': 1, 'right_users': 0, 'control_users': 0}, 
// {'channel': 'aviation world', 'left_users': 1, 'right_users': 0, 'control_users': 0}, 
// {'channel': 'johnny carson', 'left_users': 1, 'right_users': 0, 'control_users': 0}, 
// {'channel': 'the new york times', 'left_users': 1, 'right_users': 0, 'control_users': 0}, 
// {'channel': 'sky news australia', 'left_users': 1, 'right_users': 9, 'control_users': 0}, 
// {'channel': 'saturday night live', 'left_users': 1, 'right_users': 4, 'control_users': 0}, 
// {'channel': 'jeff dunham', 'left_users': 1, 'right_users': 0, 'control_users': 0}, 
// {'channel': 'talent recap uk', 'left_users': 1, 'right_users': 0, 'control_users': 0}, 
// {'channel': 'abc news in depth', 'left_users': 1, 'right_users': 0, 'control_users': 0}, 
// {'channel': 'cbc news', 'left_users': 1, 'right_users': 0, 'control_users': 0}, 
// {'channel': 'the graham norton show', 'left_users': 0, 'right_users': 1, 'control_users': 0}, 
// {'channel': 'next of ken', 'left_users': 0, 'right_users': 1, 'control_users': 0}, 
// {'channel': 'wrestlingfanatic08', 'left_users': 0, 'right_users': 1, 'control_users': 0}, 
// {'channel': 'katie couric', 'left_users': 0, 'right_users': 1, 'control_users': 0}, 
// {'channel': 'mango news', 'left_users': 0, 'right_users': 1, 'control_users': 0}, 
// {'channel': 'amazon prime video nederland', 'left_users': 0, 'right_users': 1, 'control_users': 0}, 
// {'channel': 'subaru', 'left_users': 0, 'right_users': 1, 'control_users': 0}, 
// {'channel': 'global news', 'left_users': 0, 'right_users': 1, 'control_users': 0}, 
// {'channel': 'scott manley', 'left_users': 0, 'right_users': 1, 'control_users': 0}, 
// {'channel': 'forbes breaking news', 'left_users': 0, 'right_users': 1, 'control_users': 0}, 
// {'channel': 'history', 'left_users': 0, 'right_users': 1, 'control_users': 0}, 
// {'channel': 'mercury news', 'left_users': 0, 'right_users': 1, 'control_users': 0}]

export default [{'channel': 'pbs newshour', 'left_users': 22, 'right_users': 7, 'control_users': 18}, {'channel': 'sky news', 'left_users': 19, 'right_users': 1, 'control_users': 17}, {'channel': 'today', 'left_users': 9, 'right_users': 8, 'control_users': 12}, {'channel': 'fox news', 'left_users': 0, 'right_users': 31, 'control_users': 1}, {'channel': 'nbc news', 'left_users': 10, 'right_users': 6, 'control_users': 10}, {'channel': 'lastweektonight', 'left_users': 2, 'right_users': 2, 'control_users': 2}, {'channel': 'cnn', 'left_users': 8, 'right_users': 7, 'control_users': 3}, {'channel': 'cbs news', 'left_users': 3, 'right_users': 0, 'control_users': 10}, {'channel': 'sky news australia', 'left_users': 1, 'right_users': 9, 'control_users': 0}, {'channel': 'yahoo finance', 'left_users': 0, 'right_users': 0, 'control_users': 7}]
